version: '3.9'

services:
  openbabel:
    build:
      context: openbabel
      dockerfile: Dockerfile
    image: firesimulations/openbabel:3.1.1
    container_name: openbabel
    tty: true
    stdin_open: true
    networks:
      - openbabel_net

  rdkit:
    build:
      context: rdkit
      dockerfile: Dockerfile
    image: firesimulations/rdkit:2024.03.1
    container_name: rdkit
    tty: true
    stdin_open: true
    networks:
      - openbabel_net
  
  autodocking:
    build:
      context: autodocking
      dockerfile: Dockerfile
    image: firesimulations/autodocking:2024.4.14
    container_name: autodocking
    tty: true
    stdin_open: true
    volumes:
      - ./autodocking/bin:/ubin
      - ./autodocking/specs.json:/tmp/specs.json
      - ./autodocking/specs.txt:/tmp/specs.txt
    environment:
      - COMPOSE_DOCKER_CLI_BUILD=1
      - DOCKER_BUILDKIT=1
      - DOCKER_DEFAULT_PLATFORM=linux/amd64,linux/arm64
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - openbabel_net
  
  autodocking-test:
    build:
      context: autodocking-test
      dockerfile: Dockerfile
    image: firesimulations/autodocking-test:0.0.1
    container_name: autodocking-test
    tty: true
    stdin_open: true
    networks:
      - openbabel_net

networks:
  openbabel_net:
    driver: bridge
