dependencies:
  - python >=3.9,<=3.11
  - openbabel
  - mgltools
  - zlib
  - pip
  - numpy
  - scipy
  - rdkit
  - pip:
      - vina
      - meeko
      - biopandas
      - py3Dmol
      - autopep8
      - pydantic[email]