---

name: Build and push rdkit

env:
  docker_repo: firesimulations/rdkit

on:
  push:
    branches:
      - 'master'

jobs:
  rdkit-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:rdkit"
          push: true
          tags: ${{env.docker_repo}}:3.1.1,${{env.docker_repo}}:latest
